POST https://web1s.com/continue

Content-Type: multipart/form-data

screen: 1920 x 1080
browser: Chrome
browserVersion: 111.0.0.0
browserMajorVersion: 111
mobile: false
os: Windows
osVersion: 10
cookies: true
flashVersion: no check
code: SymBAXvs4k
client_id: ffa91e2b-a10f-49e5-b3e1-163b4300751b
pathname: /
href: https://fun88vnd.com/
hostname: fun88vnd.com